import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef, useState } from "react";
import Tips from "@/components/Tips/Tips";
import { ToastContainer, toast } from "react-toastify";
import Attempts from "@/components/Attempts/Attempts";

export default function Home() {
  const [randomNumer, setRandomNumber] = useState<number>(0);
  const [winGame, setWinGame] = useState<boolean>(false);
  const [attempts, setAttempts] = useState<number[]>([]);
  const [showTips, setShowTips] = useState<boolean>(false);
  const [tipsContent, setTipsContent] = useState<string[]>([
    "considere começar o primeiro chute pelo meio do número total",
    "comece definindo um número minímo e máximo onde o valor do chute será o resultado de: (min + max) / 2 = X",
  ]);
  const refNumber = useRef<HTMLInputElement>(null);
  const notifyInfo = (content: string) => toast.info(content);
  const notifySuccess = (content: string) => toast.success(content);

  function getRandomNumber() {
    setRandomNumber(Math.floor(Math.random() * 100) + 1);
  }

  function countAttempts(value: number) {
    if (attempts.includes(value)) {
      return;
    }
    setAttempts([...attempts, value]);
  }

  function enableTips() {
    if (!showTips) {
      setShowTips(true);
      return;
    }
    setShowTips(false);
  }
  function generateTips(content: string) {
    if (tipsContent.includes(content)) {
      return;
    }
    setTipsContent([...tipsContent, content]);
  }

  function checkNumber() {
    if (!!refNumber.current?.value) {
      const numberInsert = parseInt(refNumber.current?.value);
      countAttempts(numberInsert);

      if (numberInsert === randomNumer) {
        notifySuccess("Parabéns, você acertou o número");
        setWinGame(true);
      }

      if (numberInsert > randomNumer) {
        generateTips(
          `Caso número inserido for maior, realize a atribuição do seu chute anterior no valor máximo e subtraia - 1 aplicando a fórmula novamente: (min + max) / 2 = X`
        );
        notifyInfo("Número inserido é maior, digite um número menor");
      }

      if (numberInsert < randomNumer) {
        generateTips(
          `Caso número inserido for menor, realize a atribuição do seu chute anterior no valor mínimo e some + 1 aplicando a fórmula novamente: (min + max) / 2 = X`
        );
        notifyInfo("Número inserido é menor, digite um número maior");
      }
    }
  }

  function resetGame() {
    getRandomNumber();
    setWinGame(false);
    setAttempts([]);
    setShowTips(false);
    setTipsContent([
      "considere começar o primeiro chute pelo meio do número total",
      "comece definindo um número minímo e máximo onde o valor do chute será o resultado de: (min + max) / 2 = X",
    ]);
  }

  useEffect(() => {
    getRandomNumber();
  }, []);
  return (
    <>
      <Head>
        <title>Pesquisa binária</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.container}>
          <div className={styles.title}>
            <h3>
              {" "}
              {winGame
                ? `Parabéns você acertou!!! 🤟🤪 O número misterioso era ${randomNumer}`
                : "Estou pensando em um número de 1 a 100. Adivinhe qual é ? 🤔"}
            </h3>
            {!winGame && (
              <p>Estou pensando em um número de 1 a 100. Adivinhe qual é ?</p>
            )}
          </div>
          <div className={styles.content}>
            <div className={styles.input}>
              <label>Digite um número</label>
              <input ref={refNumber} type="number"></input>
            </div>
            <button onClick={() => checkNumber()}>Verificar</button>
            <div className={styles.attempts}>
              <span>Já tentou: {attempts.length} tentativa(s)</span>
            </div>

            {attempts.length > 0 && (
                <Attempts numbers={attempts}/>   
            )}
            
            {showTips && <Tips content={tipsContent} />}
          </div>

          <div className={styles.buttons}>
            <button onClick={() => resetGame()}>Resetar jogo</button>
            <button onClick={() => enableTips()}>
              {showTips ? "Ocultar dicas" : "Exibir dicas"}
            </button>
          </div>
          <div className={styles.footer}>
          <h4>Made with 💙 by <a href="https://www.linkedin.com/in/giovanni-sena/" target="_blank">Giovanni Lima</a></h4>
          </div>
        </section>
        <ToastContainer />
      </main>
    </>
  );
}
